### ISSUE TITLE
 429 Client Error: Too Many Requests for url: https://api.coinmarketcap.com/v1/global

### ISSUE THREAD

**Issue by Menox10** [ZoranPandovski/pycoincap#12]
For a few days I had no updates anymore. One per hour I receive the data with python 2.7 on raspberry pi. I also tried with python3 with latest code but the example on your site also does not work for a single call.

I see that they now offer a basic free account but you need to sign-up and have API keys. So I hope you can make a version for this so we still can use your beautiful program!

**Comment by ZoranPandovski** [comment]
Hi @Menox10. Public API Version 1 was taken offline on November 30th, 2018. I have created issues to upgrade module for Version 2.
